In [2]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [3]:
import pandas as pd
import numpy as np
import sklearn as sk

In [4]:
df = pd.read_csv('loan_data/loan_data_tableau.csv')

In [5]:
pd.options.display.max_columns = None
df.head(5)

,id,loan_amnt,term,int_rate,installment,sub_grade,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,purpose,dti,delinq_2yrs,inq_last_6mths,open_acc,revol_bal,revol_util,total_acc,pub_rec_bankruptcies,fed_reserve_region,last_credit_pull_datetime,grade,addr_state
0,1077430,2500,60,15.27,59.83,C4,0,RENT,30000.0,Source Verified,Dec-11,Charged Off,car,1.00,0,5,3,1687,0.09,4,0.0,6,2013-09-01,C,GA
1,1076863,10000,36,13.49,339.31,C1,10,RENT,49200.0,Source Verified,Dec-11,Fully Paid,other,20.00,0,1,10,5598,0.21,37,0.0,12,2016-04-01,C,CA
2,1075269,5000,36,7.90,156.46,A4,3,RENT,36000.0,Source Verified,Dec-11,Fully Paid,wedding,11.20,0,3,9,7963,0.28,12,0.0,12,2016-01-01,A,AZ
3,1069639,7000,60,15.96,170.08,C5,8,RENT,47004.0,Not Verified,Dec-11,Fully Paid,debt_consolidation,23.51,0,1,7,17726,0.86,11,0.0,5,2016-05-01,C,NC
4,1072053,3000,36,18.64,109.43,E1,9,RENT,48000.0,Source Verified,Dec-11,Fully Paid,car,5.35,0,2,4,8221,0.88,4,0.0,12,2014-12-01,E,CA

In [6]:
df = df.drop('verification_status', axis=1)

In [7]:
df.columns

Index(['id', 'loan_amnt', 'term', 'int_rate', 'installment', 'sub_grade',
       'emp_length', 'home_ownership', 'annual_inc', 'issue_d', 'loan_status',
       'purpose', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'revol_bal', 'revol_util', 'total_acc', 'pub_rec_bankruptcies',
       'fed_reserve_region', 'last_credit_pull_datetime', 'grade',
       'addr_state'],
      dtype='object')

In [8]:
cols =['Applicant Id', 'loan Amount', 'Loan Term', 'Interest Rate', 'Installment', 'Subgrade',
       'Employment Length (Years)', 'Home Ownership', 'Annual Income',
       'Date of Issue', 'Loan Status', 'Purpose', 'Debt to Income Ratio', 'Number of Delinquencies Over Past Two Years',
       'Number of Credit Inquiries Past 6 Months', 'Number of Open Credit Lines', 'Total Credit', 'Ratio of Total Credit Utilized', 'Total Number of Credit Lines',
       'Number of Recent Bankruptcies', 'Federal Reserve Region',
       'Date of Last Credit Pull', 'Grade', 'State of Address']

In [9]:
df.columns = cols

In [10]:
month_dict = {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6, 'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 
             'Nov': 11, 'Dec': 12}

In [11]:
issue_d_list = list(df['Date of Issue'])

In [12]:
issue_d_dict = {}

sep_date = issue_d_list[0].split('-')
month = sep_date[0]
year = sep_date[1]

issue_d_dict['year'] = ['20'+year]
issue_d_dict['month'] = [month_dict[month]]

for i in np.arange(1, len(issue_d_list)):
    sep_date = issue_d_list[i].split('-')
    month = sep_date[0]
    year = sep_date[1]
    
    issue_d_dict['year'].append('20'+year)
    issue_d_dict['month'].append(month_dict[month])

In [13]:
dfissue_dates = pd.DataFrame(issue_d_dict)
dfissue_dates['day'] = '1'

In [14]:
df['Date of Issue'] = pd.to_datetime(dfissue_dates)

In [15]:
df['Number of Recent Bankruptcies'] = df['Number of Recent Bankruptcies'].astype('int')

In [16]:
df.to_csv('loan_data/loan_data_tableau_final.csv', index=False)

In [17]:
df1=df.sample(n=1000)
df1

,Applicant Id,loan Amount,Loan Term,Interest Rate,Installment,Subgrade,Employment Length (Years),Home Ownership,Annual Income,Date of Issue,Loan Status,Purpose,Debt to Income Ratio,Number of Delinquencies Over Past Two Years,Number of Credit Inquiries Past 6 Months,Number of Open Credit Lines,Total Credit,Ratio of Total Credit Utilized,Total Number of Credit Lines,Number of Recent Bankruptcies,Federal Reserve Region,Date of Last Credit Pull,Grade,State of Address
6913,866155,4200,36,5.42,126.68,A1,5,MORTGAGE,84000.0,2011-09-01,Fully Paid,major_purchase,7.26,0,0,11,13017,0.39,21,0,10,2014-04-01,A,CO
34594,362574,12000,36,13.99,410.08,D3,1,OWN,50000.0,2008-11-01,Fully Paid,debt_consolidation,12.14,0,3,11,12651,0.86,19,0,1,2011-08-01,D,MA
17673,636225,15000,36,14.17,513.91,C5,5,MORTGAGE,80000.0,2011-02-01,Fully Paid,small_business,8.46,0,2,8,1073,0.08,13,0,12,2014-02-01,C,OR
1073,1051404,3500,36,10.65,114.01,B2,10,MORTGAGE,57700.0,2011-12-01,Fully Paid,small_business,12.40,0,1,14,2104,0.05,30,0,12,2016-05-01,B,NV
8755,836363,4500,36,5.42,135.72,A1,1,MORTGAGE,70000.0,2011-08-01,Fully Paid,credit_card,12.50,0,0,8,4474,0.48,19,0,7,2014-01-01,A,IL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19808,629099,3000,36,6.91,92.51,A5,3,RENT,28000.0,2010-12-01,Fully Paid,other,7.80,0,3,5,830,0.09,8,0,4,2016-04-01,A,OH
27057,510886,10000,36,7.14,309.40,A3,5,MORTGAGE,38400.0,2010-05-01,Fully Paid,home_improvement,10.97,0,0,6,1589,0.11,18,0,9,2013-05-01,A,SD
34361,368143,4000,36,13.47,135.70,C4,10,RENT,39996.0,2008-12-01,Charged Off,debt_consolidation,8.55,0,1,5,3469,0.57,11,0,2,2010-12-01,C,NY
31164,448433,12800,36,13.57,434.80,C3,0,RENT,70000.0,2009-10-01,Fully Paid,debt_consolidation,16.30,0,2,7,17304,0.90,27,0,8,2015-11-01,C,KY
33762,383004,8000,36,13.16,270.17,C3,0,RENT,50000.0,2009-03-01,Fully Paid,debt_consolidation,19.51,0,0,4,7936,0.51,23,0,10,2016-05-01,C,CO

In [19]:
df2=df1.reset_index()
df2

,index,Applicant Id,loan Amount,Loan Term,Interest Rate,Installment,Subgrade,Employment Length (Years),Home Ownership,Annual Income,Date of Issue,Loan Status,Purpose,Debt to Income Ratio,Number of Delinquencies Over Past Two Years,Number of Credit Inquiries Past 6 Months,Number of Open Credit Lines,Total Credit,Ratio of Total Credit Utilized,Total Number of Credit Lines,Number of Recent Bankruptcies,Federal Reserve Region,Date of Last Credit Pull,Grade,State of Address
0,6913,866155,4200,36,5.42,126.68,A1,5,MORTGAGE,84000.0,2011-09-01,Fully Paid,major_purchase,7.26,0,0,11,13017,0.39,21,0,10,2014-04-01,A,CO
1,34594,362574,12000,36,13.99,410.08,D3,1,OWN,50000.0,2008-11-01,Fully Paid,debt_consolidation,12.14,0,3,11,12651,0.86,19,0,1,2011-08-01,D,MA
2,17673,636225,15000,36,14.17,513.91,C5,5,MORTGAGE,80000.0,2011-02-01,Fully Paid,small_business,8.46,0,2,8,1073,0.08,13,0,12,2014-02-01,C,OR
3,1073,1051404,3500,36,10.65,114.01,B2,10,MORTGAGE,57700.0,2011-12-01,Fully Paid,small_business,12.40,0,1,14,2104,0.05,30,0,12,2016-05-01,B,NV
4,8755,836363,4500,36,5.42,135.72,A1,1,MORTGAGE,70000.0,2011-08-01,Fully Paid,credit_card,12.50,0,0,8,4474,0.48,19,0,7,2014-01-01,A,IL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,19808,629099,3000,36,6.91,92.51,A5,3,RENT,28000.0,2010-12-01,Fully Paid,other,7.80,0,3,5,830,0.09,8,0,4,2016-04-01,A,OH
996,27057,510886,10000,36,7.14,309.40,A3,5,MORTGAGE,38400.0,2010-05-01,Fully Paid,home_improvement,10.97,0,0,6,1589,0.11,18,0,9,2013-05-01,A,SD
997,34361,368143,4000,36,13.47,135.70,C4,10,RENT,39996.0,2008-12-01,Charged Off,debt_consolidation,8.55,0,1,5,3469,0.57,11,0,2,2010-12-01,C,NY
998,31164,448433,12800,36,13.57,434.80,C3,0,RENT,70000.0,2009-10-01,Fully Paid,debt_consolidation,16.30,0,2,7,17304,0.90,27,0,8,2015-11-01,C,KY
999,33762,383004,8000,36,13.16,270.17,C3,0,RENT,50000.0,2009-03-01,Fully Paid,debt_consolidation,19.51,0,0,4,7936,0.51,23,0,10,2016-05-01,C,CO

In [21]:
print(df2.to_html(index=False, classes=["table table-striped table-hover"]))

<table border="1" class="dataframe table table-striped table-hover">
  <thead>
    <tr style="text-align: right;">
      <th>index</th>
      <th>Applicant Id</th>
      <th>loan Amount</th>
      <th>Loan Term</th>
      <th>Interest Rate</th>
      <th>Installment</th>
      <th>Subgrade</th>
      <th>Employment Length (Years)</th>
      <th>Home Ownership</th>
      <th>Annual Income</th>
      <th>Date of Issue</th>
      <th>Loan Status</th>
      <th>Purpose</th>
      <th>Debt to Income Ratio</th>
      <th>Number of Delinquencies Over Past Two Years</th>
      <th>Number of Credit Inquiries Past 6 Months</th>
      <th>Number of Open Credit Lines</th>
      <th>Total Credit</th>
      <th>Ratio of Total Credit Utilized</th>
      <th>Total Number of Credit Lines</th>
      <th>Number of Recent Bankruptcies</th>
      <th>Federal Reserve Region</th>
      <th>Date of Last Credit Pull</th>
      <th>Grade</th>
      <th>State of Address</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>6913</td>
      <td>866155</td>
      <td>4200</td>
      <td>36</td>
      <td>5.42</td>
      <td>126.68</td>
      <td>A1</td>
      <td>5</td>
      <td>MORTGAGE</td>
      <td>84000.00</td>
      <td>2011-09-01</td>
      <td>Fully Paid</td>
      <td>major_purchase</td>
      <td>7.26</td>
      <td>0</td>
      <td>0</td>
      <td>11</td>
      <td>13017</td>
      <td>0.39</td>
      <td>21</td>
      <td>0</td>
      <td>10</td>
      <td>2014-04-01</td>
      <td>A</td>
      <td>CO</td>
    </tr>
    <tr>
      <td>34594</td>
      <td>362574</td>
      <td>12000</td>
      <td>36</td>
      <td>13.99</td>
      <td>410.08</td>
      <td>D3</td>
      <td>1</td>
      <td>OWN</td>
      <td>50000.00</td>
      <td>2008-11-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>12.14</td>
      <td>0</td>
      <td>3</td>
      <td>11</td>
      <td>12651</td>
      <td>0.86</td>
      <td>19</td>
      <td>0</td>
      <td>1</td>
      <td>2011-08-01</td>
      <td>D</td>
      <td>MA</td>
    </tr>
    <tr>
      <td>17673</td>
      <td>636225</td>
      <td>15000</td>
      <td>36</td>
      <td>14.17</td>
      <td>513.91</td>
      <td>C5</td>
      <td>5</td>
      <td>MORTGAGE</td>
      <td>80000.00</td>
      <td>2011-02-01</td>
      <td>Fully Paid</td>
      <td>small_business</td>
      <td>8.46</td>
      <td>0</td>
      <td>2</td>
      <td>8</td>
      <td>1073</td>
      <td>0.08</td>
      <td>13</td>
      <td>0</td>
      <td>12</td>
      <td>2014-02-01</td>
      <td>C</td>
      <td>OR</td>
    </tr>
    <tr>
      <td>1073</td>
      <td>1051404</td>
      <td>3500</td>
      <td>36</td>
      <td>10.65</td>
      <td>114.01</td>
      <td>B2</td>
      <td>10</td>
      <td>MORTGAGE</td>
      <td>57700.00</td>
      <td>2011-12-01</td>
      <td>Fully Paid</td>
      <td>small_business</td>
      <td>12.40</td>
      <td>0</td>
      <td>1</td>
      <td>14</td>
      <td>2104</td>
      <td>0.05</td>
      <td>30</td>
      <td>0</td>
      <td>12</td>
      <td>2016-05-01</td>
      <td>B</td>
      <td>NV</td>
    </tr>
    <tr>
      <td>8755</td>
      <td>836363</td>
      <td>4500</td>
      <td>36</td>
      <td>5.42</td>
      <td>135.72</td>
      <td>A1</td>
      <td>1</td>
      <td>MORTGAGE</td>
      <td>70000.00</td>
      <td>2011-08-01</td>
      <td>Fully Paid</td>
      <td>credit_card</td>
      <td>12.50</td>
      <td>0</td>
      <td>0</td>
      <td>8</td>
      <td>4474</td>
      <td>0.48</td>
      <td>19</td>
      <td>0</td>
      <td>7</td>
      <td>2014-01-01</td>
      <td>A</td>
      <td>IL</td>
    </tr>
    <tr>
      <td>2124</td>
      <td>1036042</td>
      <td>12000</td>
      <td>36</td>
      <td>11.71</td>
      <td>396.92</td>
      <td>B3</td>
      <td>4</td>
      <td>MORTGAGE</td>
      <td>36000.00</td>
      <td>2011-11-01</td>
      <td>Fully Paid</td>
      <td>credit_card</td>
      <td>19.13</td>
      <td>0</td>
      <td>0</td>
      <td>6</td>
      <td>11360</td>
      <td>0.88</td>
      <td>9</td>
      <td>0</td>
      <td>8</td>
      <td>2014-12-01</td>
      <td>B</td>
      <td>AR</td>
    </tr>
    <tr>
      <td>33171</td>
      <td>400735</td>
      <td>1000</td>
      <td>36</td>
      <td>11.26</td>
      <td>32.87</td>
      <td>B2</td>
      <td>10</td>
      <td>RENT</td>
      <td>58000.00</td>
      <td>2009-05-01</td>
      <td>Fully Paid</td>
      <td>car</td>
      <td>15.41</td>
      <td>0</td>
      <td>3</td>
      <td>5</td>
      <td>16302</td>
      <td>0.72</td>
      <td>24</td>
      <td>0</td>
      <td>12</td>
      <td>2010-06-01</td>
      <td>B</td>
      <td>UT</td>
    </tr>
    <tr>
      <td>7204</td>
      <td>862589</td>
      <td>30000</td>
      <td>36</td>
      <td>17.99</td>
      <td>1084.43</td>
      <td>E1</td>
      <td>4</td>
      <td>MORTGAGE</td>
      <td>124000.00</td>
      <td>2011-09-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>19.95</td>
      <td>0</td>
      <td>0</td>
      <td>16</td>
      <td>31595</td>
      <td>0.86</td>
      <td>41</td>
      <td>0</td>
      <td>10</td>
      <td>2014-09-01</td>
      <td>E</td>
      <td>CO</td>
    </tr>
    <tr>
      <td>26958</td>
      <td>509250</td>
      <td>10000</td>
      <td>36</td>
      <td>11.36</td>
      <td>329.10</td>
      <td>B5</td>
      <td>7</td>
      <td>MORTGAGE</td>
      <td>50004.00</td>
      <td>2010-05-01</td>
      <td>Charged Off</td>
      <td>debt_consolidation</td>
      <td>14.69</td>
      <td>0</td>
      <td>3</td>
      <td>12</td>
      <td>5485</td>
      <td>0.27</td>
      <td>24</td>
      <td>0</td>
      <td>4</td>
      <td>2016-05-01</td>
      <td>B</td>
      <td>OH</td>
    </tr>
    <tr>
      <td>24539</td>
      <td>553313</td>
      <td>7000</td>
      <td>36</td>
      <td>13.98</td>
      <td>239.18</td>
      <td>C3</td>
      <td>1</td>
      <td>RENT</td>
      <td>32400.00</td>
      <td>2010-07-01</td>
      <td>Fully Paid</td>
      <td>other</td>
      <td>11.37</td>
      <td>0</td>
      <td>3</td>
      <td>5</td>
      <td>7039</td>
      <td>0.62</td>
      <td>7</td>
      <td>0</td>
      <td>9</td>
      <td>2016-03-01</td>
      <td>C</td>
      <td>MN</td>
    </tr>
    <tr>
      <td>19569</td>
      <td>632716</td>
      <td>8000</td>
      <td>36</td>
      <td>6.54</td>
      <td>245.34</td>
      <td>A4</td>
      <td>6</td>
      <td>RENT</td>
      <td>100000.00</td>
      <td>2010-12-01</td>
      <td>Fully Paid</td>
      <td>house</td>
      <td>22.42</td>
      <td>0</td>
      <td>5</td>
      <td>9</td>
      <td>9021</td>
      <td>0.23</td>
      <td>20</td>
      <td>0</td>
      <td>1</td>
      <td>2012-09-01</td>
      <td>A</td>
      <td>CT</td>
    </tr>
    <tr>
      <td>30681</td>
      <td>457103</td>
      <td>5000</td>
      <td>36</td>
      <td>16.35</td>
      <td>176.65</td>
      <td>E1</td>
      <td>4</td>
      <td>RENT</td>
      <td>60000.00</td>
      <td>2009-11-01</td>
      <td>Charged Off</td>
      <td>other</td>
      <td>3.16</td>
      <td>0</td>
      <td>1</td>
      <td>2</td>
      <td>0</td>
      <td>0.00</td>
      <td>6</td>
      <td>0</td>
      <td>12</td>
      <td>2010-07-01</td>
      <td>E</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>30917</td>
      <td>451663</td>
      <td>14000</td>
      <td>36</td>
      <td>12.87</td>
      <td>470.87</td>
      <td>C1</td>
      <td>7</td>
      <td>OWN</td>
      <td>58000.00</td>
      <td>2009-11-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>4.30</td>
      <td>0</td>
      <td>0</td>
      <td>12</td>
      <td>8752</td>
      <td>0.53</td>
      <td>35</td>
      <td>0</td>
      <td>12</td>
      <td>2016-01-01</td>
      <td>C</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>33731</td>
      <td>384020</td>
      <td>12000</td>
      <td>36</td>
      <td>12.53</td>
      <td>401.60</td>
      <td>C1</td>
      <td>0</td>
      <td>RENT</td>
      <td>39000.00</td>
      <td>2009-03-01</td>
      <td>Fully Paid</td>
      <td>wedding</td>
      <td>13.75</td>
      <td>0</td>
      <td>1</td>
      <td>6</td>
      <td>8123</td>
      <td>0.57</td>
      <td>12</td>
      <td>0</td>
      <td>3</td>
      <td>2016-05-01</td>
      <td>C</td>
      <td>PA</td>
    </tr>
    <tr>
      <td>26720</td>
      <td>513499</td>
      <td>20000</td>
      <td>60</td>
      <td>17.56</td>
      <td>351.54</td>
      <td>E4</td>
      <td>4</td>
      <td>MORTGAGE</td>
      <td>80004.00</td>
      <td>2010-05-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>4.87</td>
      <td>0</td>
      <td>1</td>
      <td>7</td>
      <td>3580</td>
      <td>0.47</td>
      <td>9</td>
      <td>0</td>
      <td>1</td>
      <td>2015-05-01</td>
      <td>E</td>
      <td>CT</td>
    </tr>
    <tr>
      <td>17120</td>
      <td>674088</td>
      <td>9950</td>
      <td>36</td>
      <td>5.42</td>
      <td>300.10</td>
      <td>A1</td>
      <td>10</td>
      <td>MORTGAGE</td>
      <td>100000.00</td>
      <td>2011-02-01</td>
      <td>Fully Paid</td>
      <td>other</td>
      <td>12.94</td>
      <td>0</td>
      <td>0</td>
      <td>14</td>
      <td>30630</td>
      <td>0.32</td>
      <td>57</td>
      <td>0</td>
      <td>6</td>
      <td>2016-05-01</td>
      <td>A</td>
      <td>GA</td>
    </tr>
    <tr>
      <td>2913</td>
      <td>1008183</td>
      <td>14400</td>
      <td>36</td>
      <td>12.69</td>
      <td>483.05</td>
      <td>B5</td>
      <td>6</td>
      <td>RENT</td>
      <td>135000.00</td>
      <td>2011-11-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>12.74</td>
      <td>0</td>
      <td>0</td>
      <td>13</td>
      <td>8762</td>
      <td>0.89</td>
      <td>25</td>
      <td>0</td>
      <td>12</td>
      <td>2016-05-01</td>
      <td>B</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>15088</td>
      <td>716540</td>
      <td>4000</td>
      <td>36</td>
      <td>14.91</td>
      <td>138.49</td>
      <td>D2</td>
      <td>8</td>
      <td>MORTGAGE</td>
      <td>33996.00</td>
      <td>2011-04-01</td>
      <td>Fully Paid</td>
      <td>home_improvement</td>
      <td>16.17</td>
      <td>0</td>
      <td>1</td>
      <td>7</td>
      <td>6924</td>
      <td>0.66</td>
      <td>11</td>
      <td>0</td>
      <td>2</td>
      <td>2016-05-01</td>
      <td>D</td>
      <td>NY</td>
    </tr>
    <tr>
      <td>22702</td>
      <td>575667</td>
      <td>7200</td>
      <td>60</td>
      <td>18.67</td>
      <td>185.47</td>
      <td>F2</td>
      <td>5</td>
      <td>RENT</td>
      <td>99000.00</td>
      <td>2010-09-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>17.87</td>
      <td>0</td>
      <td>0</td>
      <td>7</td>
      <td>13329</td>
      <td>0.96</td>
      <td>11</td>
      <td>0</td>
      <td>12</td>
      <td>2016-05-01</td>
      <td>F</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>1166</td>
      <td>1052184</td>
      <td>15000</td>
      <td>36</td>
      <td>7.51</td>
      <td>466.67</td>
      <td>A3</td>
      <td>3</td>
      <td>OWN</td>
      <td>44500.00</td>
      <td>2011-12-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>26.75</td>
      <td>0</td>
      <td>0</td>
      <td>14</td>
      <td>18681</td>
      <td>0.57</td>
      <td>25</td>
      <td>0</td>
      <td>6</td>
      <td>2014-03-01</td>
      <td>A</td>
      <td>FL</td>
    </tr>
    <tr>
      <td>23019</td>
      <td>577896</td>
      <td>5500</td>
      <td>36</td>
      <td>7.51</td>
      <td>171.11</td>
      <td>A4</td>
      <td>2</td>
      <td>MORTGAGE</td>
      <td>97200.00</td>
      <td>2010-09-01</td>
      <td>Fully Paid</td>
      <td>car</td>
      <td>8.77</td>
      <td>0</td>
      <td>3</td>
      <td>10</td>
      <td>1704</td>
      <td>0.05</td>
      <td>26</td>
      <td>0</td>
      <td>5</td>
      <td>2016-05-01</td>
      <td>A</td>
      <td>WV</td>
    </tr>
    <tr>
      <td>27865</td>
      <td>487278</td>
      <td>8000</td>
      <td>36</td>
      <td>7.88</td>
      <td>250.25</td>
      <td>A5</td>
      <td>0</td>
      <td>RENT</td>
      <td>36000.00</td>
      <td>2010-04-01</td>
      <td>Fully Paid</td>
      <td>other</td>
      <td>8.50</td>
      <td>0</td>
      <td>1</td>
      <td>5</td>
      <td>0</td>
      <td>0.00</td>
      <td>12</td>
      <td>0</td>
      <td>3</td>
      <td>2012-04-01</td>
      <td>A</td>
      <td>NJ</td>
    </tr>
    <tr>
      <td>5482</td>
      <td>968864</td>
      <td>9100</td>
      <td>36</td>
      <td>6.03</td>
      <td>276.97</td>
      <td>A1</td>
      <td>10</td>
      <td>MORTGAGE</td>
      <td>75000.00</td>
      <td>2011-10-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>13.15</td>
      <td>0</td>
      <td>0</td>
      <td>13</td>
      <td>13901</td>
      <td>0.30</td>
      <td>33</td>
      <td>0</td>
      <td>11</td>
      <td>2015-05-01</td>
      <td>A</td>
      <td>TX</td>
    </tr>
    <tr>
      <td>14397</td>
      <td>729091</td>
      <td>9000</td>
      <td>36</td>
      <td>14.54</td>
      <td>309.97</td>
      <td>D1</td>
      <td>4</td>
      <td>RENT</td>
      <td>43200.00</td>
      <td>2011-04-01</td>
      <td>Fully Paid</td>
      <td>medical</td>
      <td>15.94</td>
      <td>0</td>
      <td>0</td>
      <td>7</td>
      <td>5493</td>
      <td>0.62</td>
      <td>9</td>
      <td>0</td>
      <td>12</td>
      <td>2014-02-01</td>
      <td>D</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>28856</td>
      <td>486867</td>
      <td>15000</td>
      <td>36</td>
      <td>10.99</td>
      <td>491.03</td>
      <td>B4</td>
      <td>4</td>
      <td>RENT</td>
      <td>72000.00</td>
      <td>2010-02-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>10.75</td>
      <td>0</td>
      <td>0</td>
      <td>7</td>
      <td>2561</td>
      <td>0.17</td>
      <td>13</td>
      <td>0</td>
      <td>8</td>
      <td>2012-06-01</td>
      <td>B</td>
      <td>MO</td>
    </tr>
    <tr>
      <td>4964</td>
      <td>979102</td>
      <td>4200</td>
      <td>60</td>
      <td>14.27</td>
      <td>98.32</td>
      <td>C2</td>
      <td>1</td>
      <td>RENT</td>
      <td>40000.00</td>
      <td>2011-10-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>19.62</td>
      <td>0</td>
      <td>0</td>
      <td>12</td>
      <td>5949</td>
      <td>0.45</td>
      <td>20</td>
      <td>1</td>
      <td>12</td>
      <td>2014-06-01</td>
      <td>C</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>19812</td>
      <td>629097</td>
      <td>25000</td>
      <td>36</td>
      <td>14.46</td>
      <td>860.04</td>
      <td>D2</td>
      <td>9</td>
      <td>RENT</td>
      <td>100000.00</td>
      <td>2010-12-01</td>
      <td>Charged Off</td>
      <td>debt_consolidation</td>
      <td>11.44</td>
      <td>0</td>
      <td>0</td>
      <td>6</td>
      <td>13691</td>
      <td>0.82</td>
      <td>24</td>
      <td>0</td>
      <td>12</td>
      <td>2012-09-01</td>
      <td>D</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>9481</td>
      <td>814948</td>
      <td>10000</td>
      <td>36</td>
      <td>7.49</td>
      <td>311.02</td>
      <td>A4</td>
      <td>10</td>
      <td>MORTGAGE</td>
      <td>55000.00</td>
      <td>2011-07-01</td>
      <td>Fully Paid</td>
      <td>major_purchase</td>
      <td>12.74</td>
      <td>0</td>
      <td>1</td>
      <td>9</td>
      <td>3364</td>
      <td>0.09</td>
      <td>12</td>
      <td>0</td>
      <td>1</td>
      <td>2014-08-01</td>
      <td>A</td>
      <td>MA</td>
    </tr>
    <tr>
      <td>24518</td>
      <td>553726</td>
      <td>14500</td>
      <td>60</td>
      <td>15.95</td>
      <td>352.23</td>
      <td>D4</td>
      <td>10</td>
      <td>RENT</td>
      <td>27408.00</td>
      <td>2010-08-01</td>
      <td>Charged Off</td>
      <td>debt_consolidation</td>
      <td>13.09</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>10840</td>
      <td>0.96</td>
      <td>14</td>
      <td>0</td>
      <td>12</td>
      <td>2016-05-01</td>
      <td>D</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>19534</td>
      <td>633571</td>
      <td>7500</td>
      <td>36</td>
      <td>12.61</td>
      <td>251.30</td>
      <td>C2</td>
      <td>4</td>
      <td>RENT</td>
      <td>54200.00</td>
      <td>2010-12-01</td>
      <td>Fully Paid</td>
      <td>vacation</td>
      <td>15.99</td>
      <td>0</td>
      <td>3</td>
      <td>9</td>
      <td>6271</td>
      <td>0.52</td>
      <td>20</td>
      <td>0</td>
      <td>6</td>
      <td>2014-01-01</td>
      <td>C</td>
      <td>FL</td>
    </tr>
    <tr>
      <td>9525</td>
      <td>820981</td>
      <td>3000</td>
      <td>36</td>
      <td>5.42</td>
      <td>90.48</td>
      <td>A1</td>
      <td>1</td>
      <td>MORTGAGE</td>
      <td>46000.00</td>
      <td>2011-07-01</td>
      <td>Fully Paid</td>
      <td>car</td>
      <td>16.72</td>
      <td>0</td>
      <td>0</td>
      <td>14</td>
      <td>66</td>
      <td>0.00</td>
      <td>34</td>
      <td>0</td>
      <td>11</td>
      <td>2011-09-01</td>
      <td>A</td>
      <td>TX</td>
    </tr>
    <tr>
      <td>20447</td>
      <td>618734</td>
      <td>1400</td>
      <td>36</td>
      <td>14.83</td>
      <td>48.42</td>
      <td>D3</td>
      <td>8</td>
      <td>MORTGAGE</td>
      <td>54000.00</td>
      <td>2010-11-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>23.96</td>
      <td>0</td>
      <td>3</td>
      <td>10</td>
      <td>7760</td>
      <td>0.98</td>
      <td>21</td>
      <td>0</td>
      <td>6</td>
      <td>2014-06-01</td>
      <td>D</td>
      <td>GA</td>
    </tr>
    <tr>
      <td>769</td>
      <td>1058885</td>
      <td>18000</td>
      <td>60</td>
      <td>20.89</td>
      <td>485.85</td>
      <td>F1</td>
      <td>10</td>
      <td>RENT</td>
      <td>60000.00</td>
      <td>2011-12-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>20.74</td>
      <td>0</td>
      <td>2</td>
      <td>8</td>
      <td>12411</td>
      <td>0.95</td>
      <td>19</td>
      <td>0</td>
      <td>12</td>
      <td>2016-05-01</td>
      <td>F</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>5783</td>
      <td>892349</td>
      <td>35000</td>
      <td>60</td>
      <td>17.27</td>
      <td>874.93</td>
      <td>D3</td>
      <td>10</td>
      <td>RENT</td>
      <td>100000.00</td>
      <td>2011-10-01</td>
      <td>Fully Paid</td>
      <td>small_business</td>
      <td>26.32</td>
      <td>0</td>
      <td>0</td>
      <td>13</td>
      <td>2643</td>
      <td>0.16</td>
      <td>32</td>
      <td>0</td>
      <td>12</td>
      <td>2014-04-01</td>
      <td>D</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>34555</td>
      <td>363517</td>
      <td>10200</td>
      <td>36</td>
      <td>10.20</td>
      <td>330.09</td>
      <td>B1</td>
      <td>0</td>
      <td>RENT</td>
      <td>44000.00</td>
      <td>2008-11-01</td>
      <td>Fully Paid</td>
      <td>credit_card</td>
      <td>14.37</td>
      <td>0</td>
      <td>0</td>
      <td>7</td>
      <td>14869</td>
      <td>0.47</td>
      <td>12</td>
      <td>0</td>
      <td>12</td>
      <td>2016-05-01</td>
      <td>B</td>
      <td>CA</td>
    </tr>
    <tr>
      <td>13175</td>
      <td>751373</td>
      <td>12000</td>
      <td>60</td>
      <td>14.79</td>
      <td>284.16</td>
      <td>C4</td>
      <td>8</td>
      <td>MORTGAGE</td>
      <td>54996.00</td>
      <td>2011-05-01</td>
      <td>Fully Paid</td>
      <td>debt_consolidation</td>
      <td>9.08</td>
      <td>0</td>
      <td>1</td>
      <td>14</td>
      <td>10665</td>
      <td>0.44</td>
      <td>26</td>